server:
  port: 9603

spring:
  application:
    name: admin-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 20000
        multiplier: 1.3
        max-attempts: 10000
      allow-override: true
      override-system-properties: true
  jmx:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
      enabled: true