server:
  port: 8761


logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: true

spring:
  application:
    name: service-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
