server:
  port: 8761


logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
      enabled: true

spring:
  application:
    name: service-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
