server:
  port: 9604


spring:
  application:
    name: training-service1
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 20000
        multiplier: 1.3
        max-attempts: 10000
