server:
  port: 9602

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Developer/ws-me/training-service-setup-config
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: config-server
  jmx:
    enabled: true

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
