server:
  port: 9602

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Developer/ws-me/training-service-setup-config
          search-paths: 'services/{application},environments/{profile}'
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: config-server



logging:
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
